import Anthropic from '@anthropic-ai/sdk';
import { db } from '../config/database.js';
import { bestPractices } from '../db/schema.js';
import { eq, and } from 'drizzle-orm';

const SUPPORTED_INDUSTRIES = ['agency', 'fitness', 'healthcare', 'saas', 'professional-services', 'ecommerce'];

interface GenerateInput {
  industry: string;
  teamSize: number;
  agentCount: number;
  focus?: string;
}

interface GenerateResult {
  markdown: string;
  source: 'ai' | 'fallback';
  industry: string;
  practiceCount: number;
}

// ---- Fallback templates (one per industry, used when API fails) ----

const FALLBACK_TEMPLATES: Record<string, string> = {
  agency: `# Agent Coordination Rules
# Generated by OTP (orgtp.com) -- Agency Template

## Ownership
- One seat, one owner. Every agent has exactly one job. No overlap.
- Separate blast radius. Tuning one agent must never break another.
- Color-code your agents for visual distinction across dashboards and reports.

## Communication
- Pre-computed shared state. Every data source writes to its own file. Orchestrators read files, never scan sources directly.
- Staleness detection. Flag any shared state file older than 18 hours.
- Agent message bus for direct agent-to-agent coordination without human in the loop.

## Escalation
- Agents flag and recommend. Humans decide. Earn autonomy through demonstrated reliability.
- Escalation ladder with teeth: 24h alert, 48h DM, 72h warning, 72h+ auto-escalate.
- Shadow mode before live mode. Every new agent starts read-only for 2-4 weeks.

## Client Management
- Guarantee clients get a full cross-platform view in every daily briefing.
- No news is news: flag 48+ hours of silence from top clients.
- Retention agent overrides sales agent on at-risk clients. Guardians outrank Hunters.

## Operations
- Single daily briefing compiles all agent outputs into 5 sections: URGENT, TODAY, SYSTEMS, CONTEXT, WARNINGS.
- Protect one day per week with zero meetings.
- Track billable utilization. Flag when below 20% or above 40%.

## Learning
- Every correction is a learning. Capture what failed, what to do instead, and why.
- Nightly maturity evaluation against a structured framework.
`,
};

// ---- AI Generation ----

async function loadPracticesForIndustry(industry: string): Promise<string> {
  const rows = await db.select({
    term: bestPractices.term,
    definition: bestPractices.definition,
    category: bestPractices.category,
    metadata: bestPractices.metadata,
  })
    .from(bestPractices)
    .where(and(
      eq(bestPractices.industry, industry),
      eq(bestPractices.isOriginal, true),
      eq(bestPractices.isCoordination, true),
    ))
    .orderBy(bestPractices.category, bestPractices.term);

  if (rows.length === 0) return '';

  let context = '';
  let currentCategory = '';
  for (const row of rows) {
    if (row.category !== currentCategory) {
      currentCategory = row.category;
      context += `\n## ${currentCategory}\n`;
    }
    const failureMode = (row.metadata as any)?.failureMode || '';
    context += `- **${row.term}**: ${row.definition}`;
    if (failureMode) context += ` Failure mode: ${failureMode}`;
    context += '\n';
  }

  return context;
}

export async function generateClaudeMd(input: GenerateInput): Promise<GenerateResult> {
  const { industry, teamSize, agentCount, focus } = input;

  // Load practices for context
  const practiceContext = await loadPracticesForIndustry(industry);
  const practiceCount = practiceContext ? (practiceContext.match(/^- \*\*/gm) || []).length : 0;

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    console.warn('[generator] ANTHROPIC_API_KEY not set, using fallback template');
    return {
      markdown: getFallbackTemplate(industry, teamSize, agentCount),
      source: 'fallback',
      industry,
      practiceCount: 0,
    };
  }

  try {
    const client = new Anthropic({ apiKey });

    const industryName = industry.charAt(0).toUpperCase() + industry.slice(1);
    const focusLine = focus ? `The user wants to focus especially on: ${focus}` : '';

    const prompt = `You are an expert in AI agent team coordination. Generate a complete CLAUDE.md file for a ${industryName} organization with ${teamSize} people and ${agentCount} AI agents.

The CLAUDE.md should be a practical coordination document that tells agents how to work together. It should include:
1. Team overview (org size, agent count, industry context)
2. Agent roles and ownership boundaries
3. Communication protocols (shared state, message patterns)
4. Escalation rules (what gets flagged vs automated)
5. Data conventions (sources of truth, staleness rules)
6. Client/customer management rules (if applicable)
7. Operations rhythm (daily briefing, weekly review)
8. Learning and improvement protocols

${focusLine}

Here are battle-tested coordination practices from real ${industryName} AI teams to inform your output. Use these as inspiration but adapt to the specific team size and agent count:

${practiceContext || 'No industry-specific practices available. Use general best practices for multi-agent coordination.'}

Rules for the output:
- Write in imperative voice ("Do X", not "You should do X")
- Be specific and actionable, not generic
- Include concrete examples where helpful
- Use markdown headers and bullet points
- Do NOT use em dashes
- Target 800-1200 words
- Start with a comment: # Generated by OTP (orgtp.com) - [date]
- Make it immediately usable -- someone should be able to paste this into their project and have agents follow it`;

    const response = await client.messages.create({
      model: 'claude-sonnet-4-5-20250514',
      max_tokens: 2000,
      messages: [{ role: 'user', content: prompt }],
    });

    const text = response.content
      .filter((block): block is Anthropic.TextBlock => block.type === 'text')
      .map(block => block.text)
      .join('\n');

    if (!text || text.length < 100) {
      console.warn('[generator] AI response too short, using fallback');
      return {
        markdown: getFallbackTemplate(industry, teamSize, agentCount),
        source: 'fallback',
        industry,
        practiceCount,
      };
    }

    return {
      markdown: text,
      source: 'ai',
      industry,
      practiceCount,
    };
  } catch (err: any) {
    console.error('[generator] Anthropic API error:', err.message);
    return {
      markdown: getFallbackTemplate(industry, teamSize, agentCount),
      source: 'fallback',
      industry,
      practiceCount,
    };
  }
}

function getFallbackTemplate(industry: string, teamSize: number, agentCount: number): string {
  const base = FALLBACK_TEMPLATES[industry] || FALLBACK_TEMPLATES.agency!;
  const header = `# Agent Coordination Rules
# Generated by OTP (orgtp.com) -- ${industry.charAt(0).toUpperCase() + industry.slice(1)} Template
# Team: ${teamSize} people, ${agentCount} agents
# Date: ${new Date().toISOString().split('T')[0]}
# Note: This is a static template. For an AI-customized version, set ANTHROPIC_API_KEY.

`;
  // Strip the first 2 lines of the base template (they're generic headers)
  const lines = base.split('\n');
  const body = lines.slice(2).join('\n');
  return header + body;
}

export { SUPPORTED_INDUSTRIES };
